name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 如果你使用的是其他主分支，修改这里的名字

jobs:
  deploy:
    runs-on: ubuntu-latest  # 使用 ubuntu 环境构建

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 获取代码

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2  # 设置 Hugo 环境
        with:
          hugo-version: '0.101.0'  # 设置 Hugo 的版本

      - name: Build the site
        run: hugo --minify  # 执行 Hugo 构建静态网站

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # 部署到 GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # 使用自动生成的 GitHub Token
          publish_dir: ./public  # 发布文件的目录
